

version: "3"

services:

  front-end:
    build: ./front-end/

    network_mode: host
 
    depends_on:
      - back-end
  back-end:
    build: ./back-end/
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: "postgres:13.3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
